/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import modele.Compte;
import modele.RegistreCompte;
import utils.BaseDeDonnee;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.sql.*;
import javax.swing.*;

/**
 * @author lafon
 */
public class FenCreerCompte extends javax.swing.JFrame {
    private JFrame fenSeConnecter;
    private RegistreCompte registreCompte;
    RegistreCompte listing;

    /**
     * Creates new form FenCreerCompte
     */
    public FenCreerCompte() {
        initComponents();
        preremplirChamp();
    }

    public FenCreerCompte(JFrame fenSeConnecter, RegistreCompte registreCompte) {
        this();
        this.fenSeConnecter = fenSeConnecter;
        this.registreCompte = registreCompte;
    }

    public FenCreerCompte(RegistreCompte listing) {
        this();
        this.listing = listing;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboTypeCompte = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboGender = new javax.swing.JComboBox<>();
        txtPrenom = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtJourNaissance = new javax.swing.JTextField();
        txtMoisNaissance = new javax.swing.JTextField();
        txtAnneeNaisance = new javax.swing.JTextField();
        txtPays = new javax.swing.JTextField();
        txtPaysResidence = new javax.swing.JTextField();
        txtMotDePasse = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtMeConnecter = new javax.swing.JButton();
        btnCreer = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("CHEZ QUEBEC BANQUE ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Votre Compte bancaire");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Facile, rapide, sécurisé");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Vos information personnelles");

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("CHEZ QUEBEC BANQUE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(50, 50, 50)
                                                                .addComponent(jLabel3))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addComponent(jLabel5)))
                                                .addGap(0, 33, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Je souhaite ouvrir un compte :");

        jComboTypeCompte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboTypeCompte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Courant", "�pargne"}));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Titulaire :");

        jComboGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Monsieur", "Madame", "Autre"}));

        txtPrenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrenom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrenomFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrenomFocusLost(evt);
            }
        });
        txtPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrenomActionPerformed(evt);
            }
        });

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomFocusLost(evt);
            }
        });

        txtJourNaissance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJourNaissance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtJourNaissance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJourNaissanceFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJourNaissanceFocusLost(evt);
            }
        });
        txtJourNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJourNaissanceActionPerformed(evt);
            }
        });

        txtMoisNaissance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMoisNaissance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMoisNaissance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMoisNaissanceFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMoisNaissanceFocusLost(evt);
            }
        });
        txtMoisNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoisNaissanceActionPerformed(evt);
            }
        });

        txtAnneeNaisance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAnneeNaisance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAnneeNaisance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnneeNaisanceFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnneeNaisanceFocusLost(evt);
            }
        });

        txtPays.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPays.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPays.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaysFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaysFocusLost(evt);
            }
        });

        txtPaysResidence.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPaysResidence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPaysResidence.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaysResidenceFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaysResidenceFocusLost(evt);
            }
        });

        txtMotDePasse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMotDePasse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMotDePasse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMotDePasseFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMotDePasseFocusLost(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        txtTelephone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelephone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTelephone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelephoneFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelephoneFocusLost(evt);
            }
        });

        txtAdresse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAdresse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAdresse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAdresseFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdresseFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtJourNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMoisNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAnneeNaisance))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboTypeCompte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jComboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtNom))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                        .addComponent(txtPaysResidence)
                                                        .addComponent(txtPays))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                        .addComponent(txtEmail)
                                                        .addComponent(txtMotDePasse))))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jComboTypeCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtMoisNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtAnneeNaisance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtJourNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPaysResidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));

        txtMeConnecter.setBackground(new java.awt.Color(0, 204, 0));
        txtMeConnecter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMeConnecter.setText("Me Connecter");
        txtMeConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMeConnecterActionPerformed(evt);
            }
        });

        btnCreer.setBackground(new java.awt.Color(0, 204, 0));
        btnCreer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreer.setText("Créer");
        btnCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerActionPerformed(evt);
            }
        });

        btnQuitter.setBackground(new java.awt.Color(0, 204, 0));
        btnQuitter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtMeConnecter)
                                .addGap(18, 18, 18)
                                .addComponent(btnCreer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMeConnecter)
                                        .addComponent(btnCreer)
                                        .addComponent(btnQuitter))
                                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomFocusGained(java.awt.event.FocusEvent evt) {
        if (txtNom.getText().equals("Nom")) {
            txtNom.setText("");
            txtNom.setForeground(Color.BLACK);

        }
    }

    private void txtTelephoneFocusGained(java.awt.event.FocusEvent evt) {
        if (txtTelephone.getText().equals("No de Telephone")) {
            txtTelephone.setText("");
            txtTelephone.setForeground(Color.BLACK);

        }

    }

    private void txtPrenomFocusLost(java.awt.event.FocusEvent evt) {
        if (txtPrenom.getText().isEmpty()) {
            txtPrenom.setForeground(Color.GRAY);
            txtPrenom.setText("Prenom");
        }
    }


    public static void ajouterCompte(String email, String typeCompte, String titulaire, String nomClient,
                                     String prenomClient, int jourNaissance, int moisNaissance, int anneeNaissance,
                                     String pays, String motDePasse, String ville, String telephone, String adresse) throws SQLException {

        BaseDeDonnee.query = "INSERT INTO compte (email,type_compte,titulaire, nom_client, " +
                "prenom_client,jour_naissance,mois_naissance,annee_naissance,pays_naissance,mot_de_passe, ville_resident, numero_telephone, adresse) VALUES" +
                "('" + email + "', '" + typeCompte + "','" + titulaire + "', '" + nomClient + "'," +
                " '" + prenomClient + "', " + jourNaissance + " , " + moisNaissance + " , " + anneeNaissance + "," +
                "'" + pays + "','" + motDePasse + "', '" + ville + "', '" + telephone + "', '" + adresse + "');";
        System.out.println("Insertion effectuée...");
        BaseDeDonnee.prepareStatement = BaseDeDonnee.connection.prepareStatement(BaseDeDonnee.query);
        BaseDeDonnee.prepareStatement.executeUpdate(BaseDeDonnee.query);
    }

    private void btnCreerActionPerformed(java.awt.event.ActionEvent evt) {
        boolean statut = validerDonnee();
//        if (statut) {
        Compte compte = new Compte();
        compte.setEmail(txtEmail.getText());
        compte.setTypeCompte(jComboTypeCompte.getSelectedItem().toString());
        compte.setTitulaire(jComboGender.getSelectedItem().toString());
        compte.setNomClient(txtNom.getText());
        compte.setPrenomClient(txtPrenom.getText());

        try {
            compte.setJourNaissance(Integer.parseInt(txtJourNaissance.getText()));
        } catch (NumberFormatException e) {
            e.getStackTrace();
            JOptionPane.showMessageDialog(null, "Saisir un nombre entier pour le jour de naissance\n"
                    , "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
        }

        try {
            compte.setMoisNaissance(Integer.parseInt(txtMoisNaissance.getText()));
        } catch (NumberFormatException e) {
            e.getStackTrace();
            JOptionPane.showMessageDialog(null, "Saisir un nombre entier pour le mois de naissance\n"
                    , "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
        }

        try {
            compte.setAnneeNaissance(Integer.parseInt(txtAnneeNaisance.getText()));
        } catch (NumberFormatException e) {
            e.getStackTrace();
            JOptionPane.showMessageDialog(null, "Saisir un nombre entier pour le jour de naissance\n"
                    , "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
        }


        compte.setPays(txtPaysResidence.getText());
        compte.setMotDePasse(txtMotDePasse.getText());
        compte.setVille(txtPaysResidence.getText());
        compte.setTelephone(txtTelephone.getText());
        compte.setAdresse(txtAdresse.getText());

        if (statut) {
            try {
                BaseDeDonnee.seConnecter();
                ajouterCompte(compte.getEmail(), compte.getTypeCompte(), compte.getTitulaire(),
                        compte.getNomClient(), compte.getPrenomClient(), compte.getJourNaissance(), compte.getMoisNaissance(),
                        compte.getAnneeNaissance(), compte.getPays(), compte.getMotDePasse(), compte.getVille(), compte.getTelephone(),
                        compte.getAdresse());
                BaseDeDonnee.seDeconnecter();

                JOptionPane.showMessageDialog(null, compte.getTitulaire() + " " + compte.getPrenomClient() + ", Félicatation votre compte " + compte.getTypeCompte() + " a ete creer avec succès \n"
                        , "Succès", JOptionPane.INFORMATION_MESSAGE);
                preremplirChamp();
            } catch (SQLException e) {
                System.out.println("error");
                JOptionPane.showMessageDialog(null, "Erreur d'ajout d'un compte \n"
                        , "Erreur de saisie1", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    private boolean validerDonnee() {
        boolean flag = true;
        if (txtNom.getText().isEmpty()) {
            flag = false;
            JOptionPane.showMessageDialog(null, "Hey oui !! Le nom est Obligatoire ! ",
                    "Saisie de valeurs",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (txtPrenom.getText().isEmpty()) {
            flag = false;
            JOptionPane.showMessageDialog(null, "Hey oui !! Le prénom est obligatoire !",
                    "Saisie de valeurs",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (txtPays.getText().isEmpty()) {
            flag = false;
            JOptionPane.showMessageDialog(null, "Hey oui !! Le paysest obligatoire !",
                    "Saisie de valeurs",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (txtMotDePasse.getText().isEmpty()) {
            flag = false;
            JOptionPane.showMessageDialog(null, "Hey oui !! Le mot de passe est obligatoire !",
                    "Saisie de valeurs",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (txtPaysResidence.getText().isEmpty()) {
            flag = false;
            JOptionPane.showMessageDialog(null, "Hey oui !! La ville est obligatoire !",
                    "Saisie de valeurs",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (txtEmail.getText().isEmpty()) {
            flag = false;
            JOptionPane.showMessageDialog(null, "Hey oui !! Le email est obligatoire !",
                    "Saisie de valeurs",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (txtTelephone.getText().isEmpty()) {
            flag = false;
            JOptionPane.showMessageDialog(null, "Hey oui !! Le téléphone est obligatoire !",
                    "Saisie de valeurs",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (txtAdresse.getText().isEmpty()) {
            flag = false;
            JOptionPane.showMessageDialog(null, "Hey oui !! L'adresse' est obligatoire !",
                    "Saisie de valeurs",
                    JOptionPane.ERROR_MESSAGE);
        }
        return flag;
    }

    private void preremplirChamp() {
        txtNom.setForeground(Color.GRAY);
        txtNom.setText("Nom");
        txtPrenom.setForeground(Color.GRAY);
        txtPrenom.setText("Prenom");
        txtJourNaissance.setForeground(Color.GRAY);
        txtJourNaissance.setText("Jour");
        txtMoisNaissance.setForeground(Color.GRAY);
        txtMoisNaissance.setText("Mois de naissance");
        txtAnneeNaisance.setForeground(Color.GRAY);
        txtAnneeNaisance.setText("Annee");
        txtPays.setForeground(Color.GRAY);
        txtPays.setText("Pays de naissance");
        txtMotDePasse.setForeground(Color.GRAY);
        txtMotDePasse.setText("Mot de passe");
        txtPaysResidence.setForeground(Color.GRAY);
        txtPaysResidence.setText("Pays de residence");
        txtEmail.setForeground(Color.GRAY);
        txtEmail.setText("Email");
        txtTelephone.setForeground(Color.GRAY);
        txtTelephone.setText("No de Telephone");
        txtAdresse.setForeground(Color.GRAY);
        txtAdresse.setText("Adresse");
    }


    private void txtMeConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMeConnecterActionPerformed
        this.dispose();
        FenSeConnecter fenSeConnecter = new FenSeConnecter();
        fenSeConnecter.setVisible(true);
    }//GEN-LAST:event_txtMeConnecterActionPerformed

    private void txtJourNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJourNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJourNaissanceActionPerformed

    private void txtMoisNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoisNaissanceActionPerformed

    }//GEN-LAST:event_txtMoisNaissanceActionPerformed

    private void txtMotDePasseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMotDePasseFocusGained
        if (txtMotDePasse.getText().equals("Mot de passe")) {
            txtMotDePasse.setText("");
            txtMotDePasse.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_txtMotDePasseFocusGained

    private void txtMoisNaissanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMoisNaissanceFocusLost
        if (txtMoisNaissance.getText().isEmpty()) {
            txtMoisNaissance.setForeground(Color.GRAY);
            txtMoisNaissance.setText("Mois de naissance");
        }
    }//GEN-LAST:event_txtMoisNaissanceFocusLost

    private void txtMotDePasseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMotDePasseFocusLost
        if (txtMotDePasse.getText().isEmpty()) {
            txtMotDePasse.setForeground(Color.GRAY);
            txtMotDePasse.setText("Mot de passe");
        }
    }//GEN-LAST:event_txtMotDePasseFocusLost

    private void txtMoisNaissanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMoisNaissanceFocusGained
        if (txtMoisNaissance.getText().equals("Mois de naissance")) {
            txtMoisNaissance.setText("");
            txtMoisNaissance.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_txtMoisNaissanceFocusGained

    private void txtPrenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrenomFocusGained
        if (txtPrenom.getText().equals("Prenom")) {
            txtPrenom.setText("");
            txtPrenom.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_txtPrenomFocusGained

    private void txtPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrenomActionPerformed

    private void txtPaysFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaysFocusGained
        if (txtPays.getText().equals("Pays de naissance")) {
            txtPays.setText("");
            txtPays.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_txtPaysFocusGained

    private void txtPaysResidenceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaysResidenceFocusGained
        if (txtPaysResidence.getText().equals("Pays de residence")) {
            txtPaysResidence.setText("");
            txtPaysResidence.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_txtPaysResidenceFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("Email")) {
            txtEmail.setText("");
            txtEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomFocusLost
        if (txtNom.getText().isEmpty()) {
            txtNom.setForeground(Color.GRAY);
            txtNom.setText("Nom");
        }
    }//GEN-LAST:event_txtNomFocusLost

    private void txtJourNaissanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJourNaissanceFocusGained
        if (txtJourNaissance.getText().equals("Jour")) {
            txtJourNaissance.setText("");
            txtJourNaissance.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtJourNaissanceFocusGained

    private void txtJourNaissanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJourNaissanceFocusLost
        if (txtJourNaissance.getText().isEmpty()) {
            txtJourNaissance.setForeground(Color.GRAY);
            txtJourNaissance.setText("Jour");
        }
    }//GEN-LAST:event_txtJourNaissanceFocusLost

    private void txtAnneeNaisanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnneeNaisanceFocusGained
        if (txtAnneeNaisance.getText().equals("Annee")) {
            txtAnneeNaisance.setText("");
            txtAnneeNaisance.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtAnneeNaisanceFocusGained

    private void txtAnneeNaisanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnneeNaisanceFocusLost
        if (txtAnneeNaisance.getText().isEmpty()) {
            txtAnneeNaisance.setForeground(Color.GRAY);
            txtAnneeNaisance.setText("Annee");
        }
    }//GEN-LAST:event_txtAnneeNaisanceFocusLost

    private void txtPaysFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaysFocusLost
        if (txtPays.getText().isEmpty()) {
            txtPays.setForeground(Color.GRAY);
            txtPays.setText("Pays de naissance");
        }
    }//GEN-LAST:event_txtPaysFocusLost

    private void txtTelephoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelephoneFocusLost
        if (txtTelephone.getText().isEmpty()) {
            txtTelephone.setForeground(Color.GRAY);
            txtTelephone.setText("No de Telephone");
        }
    }//GEN-LAST:event_txtTelephoneFocusLost

    private void txtAdresseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdresseFocusGained
        if (txtAdresse.getText().equals("Adresse")) {
            txtAdresse.setText("");
            txtAdresse.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtAdresseFocusGained

    private void txtAdresseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdresseFocusLost
        if (txtAdresse.getText().isEmpty()) {
            txtAdresse.setForeground(Color.GRAY);
            txtAdresse.setText("Adresse");
        }
    }//GEN-LAST:event_txtAdresseFocusLost

    private void txtPaysResidenceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaysResidenceFocusLost
        if (txtPaysResidence.getText().isEmpty()) {
            txtPaysResidence.setForeground(Color.GRAY);
            txtPaysResidence.setText("Pays de residence");
        }
    }//GEN-LAST:event_txtPaysResidenceFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().isEmpty()) {
            txtEmail.setForeground(Color.GRAY);
            txtEmail.setText("Email");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreer;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JComboBox<String> jComboGender;
    private javax.swing.JComboBox<String> jComboTypeCompte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtAnneeNaisance;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtJourNaissance;
    private javax.swing.JButton txtMeConnecter;
    private javax.swing.JTextField txtMoisNaissance;
    private javax.swing.JTextField txtMotDePasse;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPays;
    private javax.swing.JTextField txtPaysResidence;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
